#!/bin/bash

#SBATCH --partition=gpu_a100
#SBATCH --job-name=original_vanilla_final
#SBATCH --ntasks=1
#SBATCH --gpus=1
#SBATCH --time=01:00:00
#SBATCH --output=original_vanilla_final.out

module purge
module load 2023    
module load Anaconda3/2023.07-2

# Your job starts in the directory where you call sbatch
# cd $HOME/...
# Activate your environment
# conda info --envs
source activate thesis-env
source /home/knigge/.bashrc

# pip install -e /home/lknigge/augmented_llm_playground_fabian
# Run your code
set -a
. /home/lknigge/augmented_llm_playground_fabian/.env
set +a

# cd augmented_llm_playground_fabian
# python trainedrag.py
python evaluate_original.py
# srun bash test.sh
