#!/bin/bash

#SBATCH --partition=rome
#SBATCH --job-name=vampire_test
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=9
#SBATCH --time=00:20:00
#SBATCH --output=slurm_output_%A.out

module purge
module load 2023    
module load Anaconda3/2023.07-2

# Your job starts in the directory where you call sbatch
# cd $HOME/...
# Activate your environment
conda remove -n thesis-env --all
conda env create -f thesis-env.yml

# conda info --envs
# source activate thesis-env
# Run your code
# srun python ...
