defaults:
  - /jam/lm/open_ai@_here_

  - _self_


# model_name: "gpt-3.5-turbo"
# model_name: "gpt-4-turbo"
# model_name: "gpt-4o"
model_name: "gpt-4o-mini"
# model_name: "o1-mini"

stop_list: 
  - "----"
  - "----\n"

max_token: 1024
run_async: True