defaults:
  - base_config
  # - model: baseline
  # - model: langgraph
  - model: langgraph_rag
  # - datasets: logicbench
  - datasets: logicbench_rag_debug

  - _self_

batch_size: 10
model:
  lm:
    run_async: False

verbose: True
experiment_name: Debug JAM
experiment_description: Experiment on tool-augmented language models.
experiment_tracking_uri: http://127.0.0.1:5000

result_dir: ${oc.env:PROJECT_ROOT}/outputs/debug

hydra:
  run:
    dir: ${result_dir}
