- _target_: jam.datasets.LogicBench
  file_name: /home/lknigge/augmented_llm_playground_fabian/data/LogicBench/retrieved_data/binary/baseline_retrieve.jsonl
  prompt_dir: /home/lknigge/augmented_llm_playground_fabian/jam/prompts/logicbench
