- _target_: jam.datasets.LogicBench
  file_name: /home/lknigge/augmented_llm_playground_fabian/data/LogicBench/abducted_data/binary/fol_eval_debug.jsonl
  prompt_dir: /home/lknigge/augmented_llm_playground_fabian/jam/prompts/logicbench